import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		"intro",
		{
			type: "category",
			label: "Overview",
			items: [
				"overview/index",
				"overview/start-here",
				"overview/for-product-stakeholders",
				"overview/for-frontend-engineers",
				"overview/for-backend-engineers",
				"overview/for-platform-engineers",
				"overview/for-new-team-members",
				"overview/product-overview",
				"overview/project-preview",
				"overview/system-landscape",
				"overview/system-architecture",
				"overview/service-interactions",
				"overview/database-overview",
				"overview/data-flow",
				"overview/user-journeys",
				"overview/glossary",
				"overview/service-dependency-map",
				"overview/request-response-flows",
				"overview/asynchronous-workflows",
				"overview/authentication-and-trust-boundaries",
			],
		},
		{
			type: "category",
			label: "Services",
			items: [
				"services/index",
				{
					type: "category",
					label: "Frontend UI",
					items: ["services/frontend-ui/index"],
				},
				{
					type: "category",
					label: "Backend API",
					items: [
						"services/backend-api/index",
						{
							type: "category",
							label: "Synced Docs",
							items: [
								"services/backend-api/synced/overview",
								"services/backend-api/synced/architecture",
								"services/backend-api/synced/project-structure",
								"services/backend-api/synced/tech-stack",
								"services/backend-api/synced/environment",
								"services/backend-api/synced/database",
								"services/backend-api/synced/api-reference",
								"services/backend-api/synced/api-response-standard",
								{
									type: "category",
									label: "Modules",
									items: [
										{
											type: "autogenerated",
											dirName: "services/backend-api/synced/modules",
										},
									],
								},
								{
									type: "category",
									label: "Integrations",
									items: [
										{
											type: "autogenerated",
											dirName: "services/backend-api/synced/integrations",
										},
									],
								},
								{
									type: "category",
									label: "Operations",
									items: [
										{
											type: "autogenerated",
											dirName: "services/backend-api/synced/operations",
										},
									],
								},
								{
									type: "category",
									label: "Generated Artifacts",
									items: [
										{
											type: "autogenerated",
											dirName: "services/backend-api/synced/generated",
										},
									],
								},
								{
									type: "category",
									label: "Future Scope",
									items: [
										{
											type: "autogenerated",
											dirName: "services/backend-api/synced/future",
										},
									],
								},
							],
						},
					],
				},
				{
					type: "category",
					label: "Scraper API",
					items: [
						"services/scraper-api/index",
						{
							type: "category",
							label: "Synced Docs",
							items: [
								{
									type: "autogenerated",
									dirName: "services/scraper-api/synced",
								},
							],
						},
					],
				},
				{
					type: "category",
					label: "Model API",
					items: ["services/model-api/index"],
				},
			],
		},
		{
			type: "category",
			label: "Operations",
			items: [
				"operations/index",
				"operations/deployment-overview",
				"operations/environments",
				"operations/failure-scenarios",
				"operations/search-and-ask-ai",
				"operations/documentation-platform-operations",
			],
		},
		{
			type: "category",
			label: "Standards",
			items: [
				"standards/index",
				"standards/scope-and-ownership",
				"standards/information-architecture",
				"standards/naming-conventions",
				"standards/metadata-standard",
				"standards/contribution-guide",
				"standards/service-documentation-integration",
				"standards/documentation-sync-and-versioning",
				"standards/documentation-quality-standards",
				"standards/doc-templates",
				"standards/review-process",
				"standards/freshness-and-lifecycle",
				"standards/visual-asset-policy",
				"standards/structural-change-policy",
				"standards/terminology-governance",
				"standards/documentation-health-metrics",
				"standards/navigation-and-discoverability",
				"standards/scaling-and-extension-strategy",
				"standards/versioning-and-audience-strategy",
				"standards/archival-strategy",
			],
		},
		{
			type: "category",
			label: "References",
			items: [
				"references/index",
				"references/domain-entities",
				"references/integrations",
			],
		},
	],
};

export default sidebars;
