---
title: Users Module
description: Current-user profile, onboarding state, profile photo metadata, skills, experience, education, and account settings contract for the Bisakerja Backend API.
owner: backend-owner
reviewers:
  - platform-docs-maintainer
  - engineering-lead
doc_status: draft
source_repo: backend-api
source_path: docs/modules/users.md
last_reviewed: 2026-04-22
---

# Users Module

The Users module owns current-user account profile data after authentication. It supports onboarding state, basic account settings, profile photo metadata, career background, skills, experience, and education.

This module provides the profile context required by preferences, job fit scoring, skill gap analysis, and AI CV Analyzer workflows.

## Responsibility

The Users module owns:

- Current user profile read and update.
- Basic account display fields.
- Phone number update when allowed.
- Profile photo metadata.
- Onboarding status.
- User skills.
- User experience entries.
- User education entries.
- Account setting fields that are not auth credentials.

The Users module does not own:

- Password changes or credential state; those belong to Auth.
- Career preference fields; those belong to Preferences.
- Job application tracker state.
- CV analysis results or uploaded CV file lifecycle.
- Mentor-specific professional profile data, which is future scope.

## Route Prefix

Primary current-user routes:

```text
/api/v1/me
```

Optional admin or user-id routes are not part of MVP.

## Endpoint Summary

| Method  | Path                       | Auth          | Purpose                                                |
| ------- | -------------------------- | ------------- | ------------------------------------------------------ |
| `GET`   | `/api/v1/me`               | Authenticated | Get current user account and profile                   |
| `PATCH` | `/api/v1/me`               | Authenticated | Update current user basic profile and account settings |
| `PUT`   | `/api/v1/me/profile-photo` | Authenticated | Upsert profile photo metadata                          |
| `PUT`   | `/api/v1/me/skills`        | Authenticated | Replace user skill list                                |
| `PUT`   | `/api/v1/me/experience`    | Authenticated | Replace user experience list                           |
| `PUT`   | `/api/v1/me/education`     | Authenticated | Replace user education list                            |

The route set uses replacement semantics for nested profile lists in MVP. Partial item-level CRUD can be added later only if frontend workflows need it.

## Auth And Ownership Rules

- Every route requires authenticated user identity.
- Every route operates only on the current user from auth context.
- The frontend must not send `userId` to mutate current-user profile routes.
- If a route ever accepts `userId`, it must be documented as admin/internal and protected separately.
- Profile data used for AI workflows must come from backend-owned persistence, not client-supplied trusted context.

## Request Schemas

### Update Current User

```json
{
  "username": "salman",
  "phoneNumber": "+6281234567890",
  "displayName": "Salman Abdurrahman"
}
```

Validation:

| Field         | Rule                                    |
| ------------- | --------------------------------------- |
| `username`    | Optional, 3-30 chars, unique if changed |
| `phoneNumber` | Optional, valid phone number format     |
| `displayName` | Optional, 1-80 chars                    |

Email update is not part of MVP unless email re-verification is documented.

### Profile Photo Metadata

```json
{
  "storageKey": "profile-photos/user_123/avatar.jpg",
  "url": "https://cdn.example.com/profile-photos/user_123/avatar.jpg",
  "mimeType": "image/jpeg",
  "sizeBytes": 512000
}
```

Validation:

| Field        | Rule                                                      |
| ------------ | --------------------------------------------------------- |
| `storageKey` | Required, storage reference only                          |
| `url`        | Optional public or signed URL generated by storage layer  |
| `mimeType`   | Required, only `image/jpeg`, `image/png`, or `image/webp` |
| `sizeBytes`  | Required, integer, maximum `5242880` (5 MB)               |

The Users module stores metadata only. Actual upload transport can be implemented by a storage/upload layer and must not log raw file content.

### Replace User Skills

```json
{
  "skills": [
    {
      "name": "TypeScript",
      "level": "INTERMEDIATE"
    },
    {
      "name": "PostgreSQL",
      "level": "BASIC"
    }
  ]
}
```

Validation:

| Field            | Rule                                               |
| ---------------- | -------------------------------------------------- |
| `skills`         | Required array                                     |
| `skills[].name`  | Required, normalized skill name                    |
| `skills[].level` | Optional enum: `BASIC`, `INTERMEDIATE`, `ADVANCED` |

Duplicate skill names are rejected after normalization.

### Replace Experience

```json
{
  "experience": [
    {
      "title": "Backend Developer Intern",
      "company": "Example Tech",
      "employmentType": "INTERNSHIP",
      "startDate": "2025-01-01",
      "endDate": "2025-06-30",
      "isCurrent": false,
      "description": "Built REST APIs with TypeScript."
    }
  ]
}
```

Validation:

| Field            | Rule                                                                   |
| ---------------- | ---------------------------------------------------------------------- |
| `title`          | Required                                                               |
| `company`        | Optional for projects, required for work experience if policy requires |
| `employmentType` | Optional enum                                                          |
| `startDate`      | Optional ISO date                                                      |
| `endDate`        | Optional ISO date, must be after `startDate`                           |
| `isCurrent`      | Optional boolean                                                       |
| `description`    | Optional, maximum 2000 characters                                      |

When `isCurrent` is `true`, `endDate` must be empty.

### Replace Education

```json
{
  "education": [
    {
      "institution": "Universitas Contoh",
      "degree": "Bachelor",
      "fieldOfStudy": "Informatics",
      "startYear": 2021,
      "endYear": 2025
    }
  ]
}
```

Validation:

| Field          | Rule                                                       |
| -------------- | ---------------------------------------------------------- |
| `institution`  | Required, non-empty string                                 |
| `degree`       | Required, non-empty string                                 |
| `fieldOfStudy` | Required, non-empty string                                 |
| `startYear`    | Optional integer                                           |
| `endYear`      | Optional integer, must be `>= startYear` when both present |

## Response Schema

### Current User Profile

```json
{
  "success": true,
  "message": "Profile retrieved successfully",
  "data": {
    "id": "user_123",
    "username": "salman",
    "email": "salman@example.com",
    "emailVerified": true,
    "phoneNumber": "+6281234567890",
    "displayName": "Salman Abdurrahman",
    "profilePhoto": {
      "url": "https://cdn.example.com/profile-photos/user_123/avatar.jpg",
      "mimeType": "image/jpeg",
      "sizeBytes": 512000
    },
    "onboardingStatus": "IN_PROGRESS",
    "profile": {
      "careerStatus": "FRESH_GRADUATE",
      "latestRole": "Backend Developer",
      "summary": "Early-career backend developer focused on TypeScript APIs."
    },
    "skills": [
      {
        "id": "skill_123",
        "name": "TypeScript",
        "level": "INTERMEDIATE"
      }
    ],
    "experience": [],
    "education": [],
    "createdAt": "2026-04-22T00:00:00.000Z",
    "updatedAt": "2026-04-22T00:00:00.000Z"
  },
  "meta": null
}
```

Response rules:

- Do not return password hash, tokens, OTP state, or sensitive auth internals.
- Return only current user's profile.
- Keep `profile`, `skills`, `experience`, and `education` stable enough for AI payload preparation.

## Service Logic

### Get Current User

1. Require authenticated identity.
2. Load `User`, `UserProfile`, `UserSkill`, `Skill`, `UserExperience`, and `UserEducation`.
3. Shape response for frontend and AI readiness.
4. Return standard success envelope.

### Update Current User

1. Require authenticated identity.
2. Validate body.
3. Check username uniqueness when username changes.
4. Update allowed `User` and `UserProfile` fields in a transaction when needed.
5. Recompute onboarding status if updated fields affect completion.
6. Return updated current user.

### Upsert Profile Photo Metadata

1. Require authenticated identity.
2. Validate metadata.
3. Replace current profile photo metadata.
4. Do not delete physical files unless storage workflow is documented.
5. Emit audit event.

### Replace Skills

1. Require authenticated identity.
2. Validate skill list.
3. Normalize skill names.
4. Upsert missing `Skill` rows if local skill ownership is used.
5. Replace `UserSkill` rows transactionally.
6. Return updated profile.

### Replace Experience And Education

1. Require authenticated identity.
2. Validate arrays.
3. Replace current records transactionally.
4. Preserve order using an explicit `sortOrder` field if frontend order matters.
5. Return updated profile.

## Repository And Database Usage

Primary models:

- `User`
- `UserProfile`
- `UserExperience`
- `UserEducation`
- `Skill`
- `UserSkill`

Repository responsibilities:

- Load current user profile by authenticated `userId`.
- Update user-safe account fields.
- Upsert profile metadata.
- Replace nested list records transactionally.
- Enforce current-user ownership through `userId` filters.

Database rules:

- One active `UserProfile` per `User`.
- Unique `users.email`.
- Unique `users.username` if username remains user-facing.
- Unique `(userId, skillId)` for `UserSkill`.
- Do not store raw CV content in this module.

## Onboarding Status

MVP onboarding states:

| Status        | Meaning                                                                   |
| ------------- | ------------------------------------------------------------------------- |
| `PENDING`     | Account exists but required onboarding data is incomplete                 |
| `IN_PROGRESS` | User has started onboarding but not completed verification or preferences |
| `COMPLETED`   | Required profile, preference, and verification steps are complete         |

Completion criteria:

- Email is verified.
- `displayName` is present.
- `phoneNumber` is present.
- Career preferences exist.

State mapping:

- `COMPLETED` when all completion criteria are satisfied.
- `IN_PROGRESS` when at least one completion signal exists but not all completion criteria are satisfied.
- `PENDING` when no completion signal exists.

The final status computation should be centralized so Auth, Users, and Preferences do not disagree.

## Error Cases

| Case                           | Status | Error code                    |
| ------------------------------ | ------ | ----------------------------- |
| Missing auth                   | 401    | `UNAUTHENTICATED`             |
| Invalid body                   | 422    | `VALIDATION_ERROR`            |
| Duplicate username             | 409    | `USERNAME_ALREADY_REGISTERED` |
| Current user not found         | 404    | `USER_NOT_FOUND`              |
| Invalid profile photo metadata | 422    | `VALIDATION_ERROR`            |
| Invalid skill level            | 422    | `VALIDATION_ERROR`            |
| Invalid experience date range  | 422    | `VALIDATION_ERROR`            |

## Observability

Log safe structured events:

- `users.profile_viewed`
- `users.profile_updated`
- `users.profile_photo_updated`
- `users.skills_replaced`
- `users.experience_replaced`
- `users.education_replaced`

Include:

- `requestId`
- `userId`
- changed field names when safe
- result

Do not log full profile payloads, phone numbers in raw form, or uploaded file contents.

## Test Scenarios

Unit tests:

- Profile update schema accepts allowed fields and rejects auth fields.
- Skill replacement rejects duplicate skill names after normalization.
- Experience validation rejects invalid date ranges.
- Onboarding status computation is deterministic.

Integration tests:

- `GET /api/v1/me` returns only authenticated current user.
- `PATCH /api/v1/me` updates allowed fields and rejects duplicate username.
- Profile photo metadata can be upserted.
- Skill replacement updates join rows transactionally.
- Experience and education replacement do not affect auth credentials.

Route tests:

- All responses follow `docs/api-response-standard.md`.
- Missing auth returns `401`.
- Invalid body returns `422`.
- No route accepts `userId` for current-user mutation.

## Open Decisions

- Whether profile photo upload is handled by this module or a future upload module.
- Whether username remains required after MVP.
- Whether `careerStatus` lives in `UserProfile`, `UserPreference`, or both as denormalized read context.
- Whether skill taxonomy is local or imported from a shared taxonomy.

## Related Docs

- `docs/api-reference.md`
- `docs/api-response-standard.md`
- `docs/database.md`
- `docs/modules/auth.md`
- `docs/modules/preferences.md`
